### ISSUE TITLE
No able to flash esp

### ISSUE THREAD

**Issue by corzone** [me176c-dev/me176c-boot#1]
I tried to flash the esp.img on my me176cx and got the error:"FAILED (remote: Can't find OSII index!!"
Any idea what it could be?

**Comment by lambdadroid** [comment]
Do you have the Android 5.0 (Lollipop) update installed?

**Comment by corzone** [comment]
no, i have the android 4.4 installed as the lollipop update had bad battery management and was a slow compared to kitkat

**Comment by lambdadroid** [comment]
me176c-boot can only be used on Android 5.0 (Lollipop). Previous versions did not use UEFI and are therefore not compatible with me176c-boot. Sorry :/

**Comment by corzone** [comment]
oh ok thanks for helping
