### ISSUE TITLE
charger firmware not working

### ISSUE THREAD

**Issue by girst** [me176c-dev/me176c-boot#10]
I installed the stock charger firmware [as per the instructions](https://github.com/me176c-dev/me176c-boot/tree/master/examples/stock-charger). When plugging in the powered off device, or when selecting Charger from the boot menu, it will not boot the charger firmware, but instead only shows the Android robot that is part of me176c-boot.

contents of `charger.conf`:

    title    Charger
    android  /asus-charger.img
    options  androidboot.mode=charger

`sha1sum asus-charger.img`: (executed on the device; extracted from the firmware linked in the instructions)

    014e40473fb14d9055fc73a8087255bf13863ef2  asus-charger.img

I would appreciate any help about what I'm doing wrong. Is there a way to turn on logging (and how to read it)?

**Comment by stephan-gh** [comment]
It works fine for me, with the same sha1sum. What else do you have installed on the device? Not sure if it relies on some other partitions like `system` or something.

**Comment by girst** [comment]
On Wed, Apr 21, 2021 at 11:01:47AM -0700, Minecrell wrote:
>What else do you have installed on the device? Not sure if it relies on 
>some other partitions like `system` or something.

I installed postmarketOS (which requires me176c-boot) to the data 
partition. my system partition is empty (i installed pmOS to it first, 
ran out of space and moved it to data, then reformatted `system`).

It didn't occur to me that it might depend on stuff on system; do you 
happen to know how I can reinstall the system partition (maybe from the 
firmware linked in the charger instructions)?

**Comment by stephan-gh** [comment]
I'm not exactly sure which partitions it might require in which state. On my me176c I have the following installed:

- me176c-boot
- LineageOS 16 on `system` / `userdata` partition
- postmarketOS on `APD` plus rootfs on SD card

And the charger works fine. This suggests that it gets confused either by your `system` or `userdata` partition, or perhaps it's something completely different. Can just try things one by one I guess :/

To restore something on the `system` partition, you could either flash the stock ROM (https://dlcdnets.asus.com/pub/ASUS/EeePAD/ME176C/UL-K013-WW-12.10.1.36-user.zip) via TWRP, or LineageOS 16 (https://forum.xda-developers.com/t/rom-9-2019-12-13-unofficial-lineageos-16-0-for-asus-memo-pad-7-me176c-x.3929600/).

**Comment by girst** [comment]
Thanks a lot! I'll try re-flashing the stock OS onto system and 'll 
report back tomorrow.

**Comment by girst** [comment]
So, i took the UL-K013-WW-12.10.1.36-user.zip file and flashed it through TWRP (mount /external_sd, then select Install from the main menu and flash it). It worked out perfectly.

I really apprecitated your help, and your work on the me176 in general - thanks!
