### ISSUE TITLE
device not detected adb twrp mount

### ISSUE THREAD

**Issue by laguill** [me176c-dev/me176c-boot#11]
Hello,
I tried to follow your instruction to use the stock charger but adb do not see my device in Mount in TWRP

Sideload is working

TWRP 3.3.1-2019-06-09 [twrp-install](https://forum.xda-developers.com/t/recovery-2019-06-09-unofficial-twrp-3-3-1-for-asus-memo-pad-7-me176c-x.3745190/)

Can you help me on this ?

I am triing to install postmarketos

**Comment by laguill** [comment]
My device is detected in recovery once I tried Mount it is not detected anymore
I tried wipe all data but still no sucess

**Comment by stephan-gh** [comment]
Make sure you **do not press** "Mount USB Storage". ADB will stop working if you press that. You're just supposed to tick the APD line.

**Comment by laguill** [comment]
Yes thank you for this :)

Now I don't understand what I need to do to Set an additional ESP partition.
I can't see the FAT32 in TWRP to change the file system of the APD partition
Should I use FAT instead ?

What is the EFI application to place on the APD partition for postmarketos

Do I only need to wipe the partition ?

Sorry to bother you on this 
I am a noob

**Comment by stephan-gh** [comment]
The good news for postmarketOS is that you actually don't need to wipe or format the APD partition. It will be set up automatically with the `fastboot flash APD asus-me176c-bootpart.img` when installing pmOS.

Also, regarding your(?) "Fastboot rootfs failed" question on the pmOS wiki, please check the _"However, if you get an error you may need to flash it using dd via the TWRP recovery instead: "_ part on the wiki page since this is a known problem. I would recommend to avoid using the "discussion" feature on the pmOS wiki since no one checks it actively. If you have questions about pmOS you can ask in [the chat on Matrix/IRC](https://wiki.postmarketos.org/wiki/Matrix_and_IRC) or create an issue at https://gitlab.com/postmarketOS/pmaports/-/issues.

**Comment by laguill** [comment]
Thank you I tried to use this command `gzip -c asus-me176c.img | adb shell "zcat | dd of=/dev/block/by-name/system bs=4m" after` extracting and rename the rootfs img file
In verbose the file is not loading 
I only see `asus-me176c.img:` and the blinking cursor

Nothing is happening

**Comment by stephan-gh** [comment]
It can take quite some time, probably need to be patient.

**Comment by laguill** [comment]
I am using manjaro and adb seems to disconnect.
It is working better on windows
Is there an alternative to gzip ?

**Comment by stephan-gh** [comment]
If you install a Git Shell on Windows you should have the typical gzip available there.

**Comment by laguill** [comment]
When I am in twrp my device is not detected by adb
I wipe Dalvik and cache but still no sucess
I changed cable, reboot, reinstall stock rom and recovery but still no sucess

When I am in system no problem whith adb I can reboot to recovery other way 
If I am lucky my device is detected then nothing

**Comment by laguill** [comment]
Is it possible to push the files and gzp using the sd card ?

**Comment by stephan-gh** [comment]
> Is it possible to push the files and gzp using the sd card ?

Yes. You can actually also install the rootfs to the SD card if you want. (This is described on the wiki page.) That way you could do dual boot with Android.

**Comment by laguill** [comment]
I meant instead of using the adb commands
Can I put all the files in a sd card and install evrything using the install zip or img in twrp

**Comment by stephan-gh** [comment]
You can use the terminal in TWRP. It does not work with the "Install zip" option. (I'm not familiar with a "Install img" option?)

e.g.

```
# dd if=/external_sd/asus-me176c.img of=/dev/disk/by-name/userdata bs=4M
```

**Comment by laguill** [comment]
Everything is working now I don't have any more problems with the adb connexion
I don't know what I have done wrong

I still can't install postmarket os. I got the error no space left after running the gzip command
I am in touch the postmarket with thematrix server maybe they will help

Thank you again for your help

**Comment by stephan-gh** [comment]
Is this the 8 GiB version of the ME176C? It's weird that it does not have enough space.

**Comment by laguill** [comment]
No it has 16Gb of storage
Does the stock charger using a lot of spaces 
Or do I need wipe some data ?

**Comment by laguill** [comment]
I have this files in the apd folder 
![image](https://user-images.githubusercontent.com/74424947/148125490-e3beb639-536e-496c-8280-819f8dadbd6b.png)
`title    postmarketOS
volume   80868086-8086-8086-8086-000000000007
linux    /vmlinuz
initrd   /intel-ucode.img
initrd   /acpi-me176c.img
initrd   /initramfs
initrd   /initramfs-extra

# Comment this out to get more output on screen while booting
options  console=null`

I updated the pmos conf file like that
Do I have to link to the System.map and config files too ?

**Comment by stephan-gh** [comment]
>  Do I have to link to the System.map and config files too ?

No

**Comment by laguill** [comment]
I runned this command in adb shell df -h after wiping everything except apd partition
![image](https://user-images.githubusercontent.com/74424947/148176000-c1714e1d-2f5b-426d-9dea-8c590339b071.png)
Is there files that I can delet ?

**Comment by stephan-gh** [comment]
You should not need to delete any files.

It looks like I made a mistake in the flashing instructions. In the `dd` command you should not use **userdata** but just **data**:

```
gzip -c ...-asus-me176c.img | adb shell "zcat | dd of=/dev/block/by-name/data bs=4m"
```

or (from SD card)

```
dd if=/external_sd/asus-me176c.img of=/dev/disk/by-name/data bs=4M
```

Sorry for the confusion.

**Comment by laguill** [comment]
Thank you it worked

Now How can change the boot order to start on postmarketos ?

I downloaded the last img available but to update the software in pos I get this error

> Sorry, something went wrong:
Error calling StartServiceByName for org.freedesktop.fwupd:
Launch helper exited with unknown return code 1

**Comment by stephan-gh** [comment]
> Now How can change the boot order to start on postmarketos ?

You can change the default in the `loader/loader.conf`, e.g.:

```
default  android
auto-entries  no

# Uncomment this to always show the boot menu
#timeout  3
```

If you have created the pmOS boot configuration as `pmos.conf`, you could use `default pmos` there instead.

> I downloaded the last img available but to update the software in pos I get this error

I don't know anything about this error but it doesn't seem specific to the asus-me176c. Please create an issue at https://gitlab.com/postmarketOS/pmaports/-/issues or ask in the pmOS chat.

**Comment by laguill** [comment]
Thank now everything is working great.

Except when my device is turn off and in charge
I see the droid robot and not the defaut asus charger and the screen is stuck turn on

I followed your instruction with boot img and stock charger file it seems not working

**Comment by laguill** [comment]
Today I tried to install docker
But I get the error no space left on the device
After typing df -h 
It seems that I only have 2 Gib on the main partition and it is already use at 94%
Shouldn't have I alomost 16 Gib ?

**Comment by stephan-gh** [comment]
Hm, perhaps the partition was not resized to span the full partition. I would generally recommend using a SD card for pmOS if you care about space. This might also fix the problems with the stock charger, perhaps it works only if an Android system is installed on internal storage.

**Comment by laguill** [comment]
I don't understand the instructions to install postmarketos on th sd card
I tried renaming the img file like this `asus-me176c-root.img` ?
Copying the file on the sd card and then using the twrp shell is not working also

**Comment by stephan-gh** [comment]
You need to copy it to the SD card using the dd command:
![Screenshot_20220114_143125](https://user-images.githubusercontent.com/3035868/149523195-e4f71077-3c36-4cfa-9914-a21724df63ea.png)

**Comment by laguill** [comment]
Sorry about that but I am lost
First how do I find the correct block device ? I tried on manjaro after plug in my device lsblk and it is not detected
I also tried the command in adb shell but it still not worked

Then I tried the dd command in a terminal on manjaro `dd if=asus-me176c.img of=/dev/mmcblkXpY bs=4M` 
but I get permission refused
In adb shell I get 'block size 4M illegal number`

**Comment by stephan-gh** [comment]
> First how do I find the correct block device ? I tried on manjaro after plug in my device lsblk and it is not detected

Uh, what are you using to read the SD card?

> In adb shell I get 'block size 4M illegal number`

might need to write the m small in the dd command (`4m`). But be very careful when doing it from adb shell, or you might accidentally overwrite the entire internal storage of the tablet.

**Comment by laguill** [comment]
I plugged in my sd card on the asus device and then in recovery mode I tried to format the sd card

**Comment by laguill** [comment]
I finally managed to install the root img on the sd card using the card adapter on pc
1. fdisk -l
2. dd if=asus-me176c.img of=/dev/sdc bs=4M

Now in bootloader I get the error unable to mount root partition
Do I need to change something in the pmos.conf file ?
