### ISSUE TITLE
Cannot update to Android 5.0

### ISSUE THREAD

**Issue by zaphida** [me176c-dev/me176c-boot#13]
Hello, I have tried to update to Android 5.0, but every time I try, I get this error in Droidboot: No valid installer medium found. My post on xda-developers: https://forum.xda-developers.com/t/me176c-x-k013-collection-of-roms-and-updates.3012965/post-87808727
Maybe you can assist. I am in Android and xda-developers discord servers, I am Zaphdia#8028 on discord. Thanks

**Comment by stephan-gh** [comment]
I replied on Matrix (I assume that was you as well).
