### ISSUE TITLE
Tablet not working at all

### ISSUE THREAD

**Issue by alansojan2021** [me176c-dev/me176c-boot#14]
Hi, I've made a big mistake. I went on the efi menu and accidentally selected an option that now doesn't let me go back into the bios menu or even the operating system itself. When I turn on the tablet, nothing comes up; however, when I plug it in, the screen lights up with no text whatsoever. Could anyone help me with this problem? Thanks.

**Comment by stephan-gh** [comment]
Perhaps you can still access the EFI menu blindly, by plugging in an USB keyboard via OTG (must be externally powered). Keep pressing F2 to enter the setup.

Then in the setup, the key mapping is as follows:
- F1: General Help
- F2: **Previous Values**, or
- F3: **Optimized Defaults**, followed by
- F4: **Save & Exit**

I've never modified any settings in the EFI menu myself so can't tell for sure how it would work or if you need to press additional keys. AFAIK someone has succeeded with this approach at some point though.

**Comment by alansojan2021** [comment]
> Perhaps you can still access the EFI menu blindly, by plugging in an USB keyboard via OTG (must be externally powered). Keep pressing F2 to enter the setup.
> 
> Then in the setup, the key mapping is as follows:
> 
> * F1: General Help
> * F2: **Previous Values**, or
> * F3: **Optimized Defaults**, followed by
> * F4: **Save & Exit**
> 
> I've never modified any settings in the EFI menu myself so can't tell for sure how it would work or if you need to press additional keys. AFAIK someone has succeeded with this approach at some point though.

Thanks for the reply, do i press the keys in order or like how Iwould press it if the screen was actually lighting up?

**Comment by stephan-gh** [comment]
From a quick test on my device it would be like this:

1. Insert powered OTG adapter with keyboard when device is off.
2. Start pressing F2 repeatedly.
3. Device turns on and enters setup menu.
4. If you pressed often enough it already registers the F2 key press and shows "Load Previous Values?" Yes or No. Yes is pre-selected. So you could confirm with Enter or cancel with Escape.
5. If you press F4 for Save & Exit it will have the confirmation dialog again with Yes / No. Yes is pre-selected again and can be chosen with Enter.

I'm not sure what Previous Values means exactly. Perhaps you actually need F3 for Optimized Defaults. In that case you'd press F3 between step 4 and 5 and confirm it as usual with Enter.

**Comment by stephan-gh** [comment]
If you search with your favorite search engine for images of the names of these options (e.g. "load previous values bios") you can easily find equivalent pictures for better imagination :)

**Comment by alansojan2021** [comment]
Thank you so much this worked!
