### ISSUE TITLE
me302c support?

### ISSUE THREAD

**Issue by dylanmtaylor** [me176c-dev/me176c-boot#15]
This device is remarkably similar to the me302c. Any chance of getting this working?

**Comment by stephan-gh** [comment]
AFAICT this device has a Intel Atom Z2560, which is part of the "Cloverview" line and not "Bay Trail" like ME176C. These two platforms have significant differences. I'm not sure if the "Cloverview" line ever got UEFI, which would be the main requirement to get me176c-boot running.
