### ISSUE TITLE
Can't configure uefi

### ISSUE THREAD

**Issue by corzone** [me176c-dev/me176c-boot#2]
When i go to firmware interface, it works but i can't change anything as the screen doesn't respond to touch only can navigate using the volume buttons buttons.(PS:after updating to lollipop and installing this and then installing lineage os, it worked out, great work you did ;)

**Comment by lambdadroid** [comment]
First off, unless you know what you are doing, you should not touch most of the options there. It is possible to prevent the tablet from booting if you change the wrong options.

To navigate in the firmware interface, you need a USB-OTG hub with external power supply and an USB keyboard.

**Comment by corzone** [comment]
ok got it, thanks for the help ;)(as i dont have a usb hub with external power that dont start smoking as i plug in i will leave it as it is)
