### ISSUE TITLE
Recovery (instruction) not working

### ISSUE THREAD

**Issue by cskau** [me176c-dev/me176c-boot#3]
I've been trying to boot Linux on my ME176C and while the instructions have largely worked, I've run into a few issues.

Before I started doing anything with the device I booted into Android, dumping a few bits and making sure all the prerequisites were in order.
The device however came out of the box with Android 4.4.2, ro.build.asus.version=3.2.23.191, and the built-in updater didn't detect any system updates.
Luckily I managed to find instructions on how to [manually update](https://www.asus.com/us/support/FAQ/1009748/) the device, with the [available updates](https://www.asus.com/Tablets/ASUS_MeMO_Pad_7_ME176C/HelpDesk_BIOS/).
This took me from `3.2.23.191` to `12.10.1.17` to `12.10.1.36`, which matches the prerequisites.

Following the instructions I was then able to install the bootloader: `fastboot flash ESP esp.img`
From thereon though I've run into problems as the instructions seems to assume that I can boot into recovery mode, which I can't.
Regardless of whether I `adb reboot recovery` or select `recovery` in the bootloader, I end up with a simple screen just saying "Error!", and neither fastboot nor adb.

I don't know if this is a result of the manual update I did, or if this is some issue with my device.
I did notice that the box ROM had one boot mode where I ended up in a similar screen where instead it said "Brak polecenia." ("No command." in Polish??), which may or may not have been the original recovery not working.

Are there other steps involved in getting the recovery working with the bootloader?

**Comment by lambdadroid** [comment]
The recovery provided by ASUS cannot do much and will always display `Error!` unless provided with some special command file.

My instructions assume that you have [my version of TWRP](https://forum.xda-developers.com/memo-pad-7/orig-development/recovery-unofficial-twrp-3-2-1-asus-t3745190) installed. That recovery has a proper touch UI where you can make backups etc.

Also see my [Arch Linux thread on XDA](https://forum.xda-developers.com/memo-pad-7/orig-development/linux-arch-linux-asus-memo-pad-7-me176x-t3917593) and the [article on the ArchWiki](https://wiki.archlinux.org/index.php/ASUS_MeMO_Pad_7_(ME176C(X))) for additional help later. :)

**Comment by empty-fortress** [comment]
Leaving this here in case someone follows the same breadcrumbs I did: the latest (3.3.1) TWRP for me176c version doesn't seem to work on the 8Gb version of the memotab I have, but 3.2.1 does. 3.3.1 runs fine on the 16Gb model. Now you know.
I'll update the postmarketOS install wiki page with this info.

**Comment by stephan-gh** [comment]
@empty-fortress Can you open a separate issue for this at https://github.com/me176c-dev/android_device_asus_K013

It's certainly not intended, but I do not have such a device (and I'm not aware of many), so I'm not able to test it myself. I don't see anything obvious in the TWRP changelog that might break functionality on the 8 GB version.

Thanks.

**Comment by empty-fortress** [comment]
https://github.com/me176c-dev/android_device_asus_K013/issues/67

as I said, feel free to ask if you need me to try new things.

**Comment by gonchez** [comment]
> The recovery provided by ASUS cannot do much and will always display `Error!` unless provided with some special command file.
> 
> My instructions assume that you have [my version of TWRP](https://forum.xda-developers.com/memo-pad-7/orig-development/recovery-unofficial-twrp-3-2-1-asus-t3745190) installed. That recovery has a proper touch UI where you can make backups etc.
> 
> Also see my [Arch Linux thread on XDA](https://forum.xda-developers.com/memo-pad-7/orig-development/linux-arch-linux-asus-memo-pad-7-me176x-t3917593) and the [article on the ArchWiki](https://wiki.archlinux.org/index.php/ASUS_MeMO_Pad_7_(ME176C(X))) for additional help later. :)

Hi! I have the same issue when trying to get into recovery mode. So when I read TWRP installing instructions I don't know how to do it. Maybe I'm getting involved in something hard for me, without any programming knoledgement. But I find really interesting to have my ASUS tablet with PostmarketOS.
