### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by cskau** [me176c-dev/me176c-boot#4]
The link for 'set up an additional ESP partition' in the [dual-boot](https://github.com/me176c-dev/me176c-boot/tree/master/examples/multi-boot) doc is broken (404).

I'm guessing it was supposed to point to `/README.md#setting-up-an-additional-esp-partition` - i.e. it's missing the `README.md`.

**Comment by lambdadroid** [comment]
Yeah, you're right. I guess I was hoping `/` would point to https://github.com/me176c-dev/me176c-boot, where it'd work fine:

https://github.com/me176c-dev/me176c-boot#setting-up-an-additional-esp-partition
