### ISSUE TITLE
Fastboot Flashing error

### ISSUE THREAD

**Issue by ReubenBTalbott** [me176c-dev/me176c-boot#5]
Whenever I try to flash with fastboot I get the error `FAILED (remote: 'flash_cmds error!`
Do you know the solution to this issue?

Thanks!
Reuben

**Comment by ReubenBTalbott** [comment]
I have a K01A if that helps.

**Comment by stephan-gh** [comment]
Unfortunately, the K01A uses an entirely different SoC "Cloverview" instead of "Bay Trail". It is not compatible with me176c-boot and/or the LineageOS ROM, because it has a PowerVR GPU that is entirely unsupported by open-source projects. Sorry!

**Comment by ReubenBTalbott** [comment]
Thanks for the answer. You might want to specify what versions of the MeMo
pad 7 do and don't work in the read me, I bought my k01A just to install
linux on thinking it was the right model (since I did not realize there are
multiple models). I did order K013 so I hope to install linux on it once it
arrives.


Thanks for all of your work!

Reuben

**Comment by stephan-gh** [comment]
I'm sorry that you ordered the wrong model. However, I'm quite sure that I write "ASUS MeMO Pad 7 (**ME176C(X)**)" everywhere, which is the model number for the K013. K013 is the Android codename. K01A is ME70C as far I know.
