### ISSUE TITLE
Unable to flash ESP

### ISSUE THREAD

**Issue by jrobinson52** [me176c-dev/me176c-boot#6]
When attempting to flash the esp.img to the device, I get:
> RESULT: FAIL(flash_cmds error! )
I am now unable to re-flash the factory esp.img

Any ideas?

**Comment by stephan-gh** [comment]
If flashing ESP fails, then the factory one shouldn't have been modified it any way.

But I'm not sure why flashing it would fail, except for:
  - You have not updated to Android 5 (for UEFI)
  - You typed the command incorrectly (`fastboot flash ESP esp.img`, case-sensitive)

**Comment by jrobinson52** [comment]
The device is on Android 5 and I haven't mistyped the command. The img gets
sent successfully but when it attempts to flash it fails.

**Comment by stephan-gh** [comment]
Are you in the correct fastboot screen? What is displayed on the screen when you are in the fastboot interface?

**Comment by jrobinson52** [comment]
Prior to flashing I see this:
![IMG_20191206_092455](https://user-images.githubusercontent.com/31286997/70330984-9a8fa200-180c-11ea-8079-16e83dbf232f.jpg)

After flashing I see this:
![IMG_20191206_092826](https://user-images.githubusercontent.com/31286997/70331070-bb57f780-180c-11ea-8c94-0fb58d3a4a37.jpg)

Here is the software info Android is reporting:
![IMG_20191206_093041](https://user-images.githubusercontent.com/31286997/70331290-2c97aa80-180d-11ea-9f9c-f5d65e0d7b31.jpg)

**Comment by stephan-gh** [comment]
You seem to have a K01A. Unfortunately, this bootloader is for me176c ("K013"), not for your device :/
Most older devices from ASUS weren't updated with UEFI unfortunately.

**Comment by jrobinson52** [comment]
Gotcha. I misread which models were supported.

**Comment by stephan-gh** [comment]
Sorry about that :(
