### ISSUE TITLE
Cannot flash the old bootloader

### ISSUE THREAD

**Issue by ISmokeAir** [me176c-dev/me176c-boot#8]
I have tried a custom rom and I dint liked it. I want to go back to my stock rom. I am trying to flash the old bootloader and it gives me an error `Result: Fail(flash_cmds error! )`. My device is a K013. When I installed the custom bootloader i had the newest version of android available. Also, if I am doing this the wrong way, can u tell me how can I restore my stock rom? Thank you.

**Comment by stephan-gh** [comment]
In general, you can just use the stock ROM with this custom bootloader. Just flash [`UL-K013-WW-12.10.1.36-user.zip`](https://dlcdnets.asus.com/pub/ASUS/EeePAD/ME176C/UL-K013-WW-12.10.1.36-user.zip) from TWRP and do a factory reset.
